import { AuthProvider } from '@src/context/use-auth';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import Wrapper from './Wrapper';
import './globals.css';

const inter = Inter({
  display: 'swap',
  weight: 'variable',
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'Xpress Rewards',
    template: '%s | Xpress Rewards',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>
          <Wrapper>
            {children}
            <Toaster
              position="top-center"
              closeButton
              richColors
              toastOptions={{
                classNames: {
                  description: 'text-[#606060]',
                },
              }}
              theme="light"
            />
          </Wrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
